// <auto-generated />
namespace GrandeTravel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GrandeTravelMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrandeTravelMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201405040818217_GrandeTravelMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
